server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "exXkl/Q6Ud2g/xLImMZD50fun69Ppglxpf+HxME5+PSOM8Uza6EnkXMGSs4i1LV6"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

cors:
  allowed:
    origins: "http://localhost:3000"
